language: node_js
branches:
  only:
    - master
node_js:
  - '6'
install:
  - npm install
script:
  - npm run release
  - bash ./deploy.sh
env:
  global:
    - GH_REF: github.com/vogloblinsky/devfest-2016-tree-shaking-slides.git
    - secure: b3y+kpkux9n1teE9V0bUfcSIY5SbKgRpZEgQS4M6CnYpDhMI1hjzQiXRkNTDOqd0iwAFBgzhPX5+pRc4cTl2hl2jUvH66LaYGZGz/D1fHKRUTdFJcm2DBUg57vnll5nRctpDgHPThhYKMO2s8AF8QJHskXwGJjjxyrpxb3GRD/e3Q2YMT3Z3dK1McNKDAF4Valzv/lkMvfSt3CnbIte5fSgjJ/e8Spfugv0/T0yrY/BWNxot1lnXTozd94RzdQIG25TIaKCZvmh81Gtc5ZToEDLdERNL7Vd0ClBjZ5r7Ngwio5d/RJnfhlQXuQ+PRlOdqbXM84beh7Of/NgvIhCKhcrlgmGPrWW4G1gGE3umlIAJGPWT+85RxlJoRRMpWll/rrXH8+DLHvfTvJKZs7m40kUsmJumMndMeUtnGz8DTOOA2xJuUd+HGobqaKrNWPXJ9S+pfwlGNgjcbSLkFij16bMagzz2HQHUJOy0Iowbr4Zru9DEmRG6u7L3gRui9x129LSSem0asx3AGrz1LkkwH6D5G/RoBSGLiCJUjc6tuSyCGhnLpOcKJoutvZJECAClyBAbkn2WKrw7LXDGfWNU4Qp5meAL6AGfeKzV9NCmdZgmE0emQNp74XnaJBGtVaj+onwE00nnz3Ou13yH/yQz3Y+IFukrGLsG1C2s6GPcuZ8=
